nelmio_api_doc:
    documentation:
        info:
            title: My API Documentation
            version: '1.0'
        swagger:
            info:
                title: ApiRestUtilisateur
                version: 1.0.0
            host: localhost:8089
            basePath: /api
        paths:
            '%kernel.project_dir%/src/Controller':
                resource: .
                type: annotation
        models:
            auto_mapping: true
    cache: true