services:
  php:
    build: .
    container_name: user_api
    ports:
    - "8089:80"
    volumes:
      - .:/var/www/html
    networks:
      - symfony_network
    working_dir: /var/www/html
    environment:
      - APP_ENV=dev
      - APP_DEBUG=true
    command: bash -c "composer install && apache2-foreground"



  db:
    image: postgres:13-alpine
    container_name: user_database
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: api_rest_utilisateur
    volumes:
      - db_data:/var/lib/postgresql/
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - symfony_network

networks:
  symfony_network:
    driver: bridge

volumes:
  db_data:
    driver: local