openapi: 3.0.0
info:
  title: 'My API Documentation'
  version: '1.0'
paths:
  'C:\Users\Tsinjoniaina\Downloads\ITU\S5\Programmation\Web\Projet\projet-S5\ApiRestUtilisateur\ApiRestUtilisateur/src/Controller': {  }
  '/_error/{code}':
    get:
      operationId: get__preview_error
      parameters:
        -
          name: code
          in: path
          required: true
          schema:
            type: string
            pattern: \d+
      responses:
        default:
          description: ''
    put:
      operationId: put__preview_error
      parameters:
        -
          name: code
          in: path
          required: true
          schema:
            type: string
            pattern: \d+
      responses:
        default:
          description: ''
    post:
      operationId: post__preview_error
      parameters:
        -
          name: code
          in: path
          required: true
          schema:
            type: string
            pattern: \d+
      responses:
        default:
          description: ''
    delete:
      operationId: delete__preview_error
      parameters:
        -
          name: code
          in: path
          required: true
          schema:
            type: string
            pattern: \d+
      responses:
        default:
          description: ''
    options:
      operationId: options__preview_error
      parameters:
        -
          name: code
          in: path
          required: true
          schema:
            type: string
            pattern: \d+
      responses:
        default:
          description: ''
    head:
      operationId: head__preview_error
      parameters:
        -
          name: code
          in: path
          required: true
          schema:
            type: string
            pattern: \d+
      responses:
        default:
          description: ''
    patch:
      operationId: patch__preview_error
      parameters:
        -
          name: code
          in: path
          required: true
          schema:
            type: string
            pattern: \d+
      responses:
        default:
          description: ''
    trace:
      operationId: trace__preview_error
      parameters:
        -
          name: code
          in: path
          required: true
          schema:
            type: string
            pattern: \d+
      responses:
        default:
          description: ''
  /api/doc:
    get:
      operationId: get_apiDoc
      responses:
        default:
          description: ''
  /utilisateur/signup:
    get:
      operationId: get_signin
      responses:
        default:
          description: ''
  /utilisateur/signin:
    post:
      operationId: post_app_api_utilisateur_login
      responses:
        default:
          description: ''

